import test from 'node:test';
import assert from 'node:assert/strict';
import * as r from '../assets/js/services/repository.js';
import {esc} from '../assets/js/renderers.js';
import {previewMessage,simulateSend} from '../assets/js/services/notification-service.js';
test('data volumes and relational IDs',()=>{assert.ok(r.listEvents().length>=12);assert.ok(r.listPosts().length>=20);assert.ok(r.listClubs().length>=12);assert.ok(r.collection('courses').length>=8);assert.ok(r.collection('volunteerPrograms').length>=6);for(const e of r.listEvents())assert.ok(r.content('associations').some(a=>a.id===e.associationId));});
test('registration date and capacity boundaries',()=>{const e=r.getEvent('event-1');assert.equal(r.eventStatus(e,new Date('2026-08-31')),'접수예정');assert.equal(r.eventStatus(e,new Date('2026-09-17')),'접수중');assert.equal(r.eventStatus(e,new Date('2026-11-01')),'마감');assert.equal(r.eventStatus({...e,participantCount:80},new Date('2026-09-17')),'마감');});
test('combined filters and search return matching actual data',()=>{const rows=r.listEvents({sport:'골프',region:'경기',q:'그린컵'});assert.equal(rows.length,1);assert.equal(r.listEvents({q:'없는검색어'}).length,0);assert.ok(r.searchAll('골프').some(x=>x.type==='동호회'));});
test('repository values are cloned and cannot mutate source',()=>{const e=r.getEvent('event-1');e.title='changed';assert.notEqual(r.getEvent('event-1').title,'changed');});
test('guest and unknown targets rejected',()=>{r.resetDemo();assert.throws(()=>r.submitApplication({kind:'event',targetId:'event-1'}),/로그인/);r.setRole('member');assert.throws(()=>r.submitApplication({kind:'event',targetId:'bad'}),/찾을 수/);});
test('application, duplicate protection, cancellation and retry',()=>{r.resetDemo();r.setRole('member');const a=r.submitApplication({kind:'event',targetId:'event-1'});assert.ok(r.getMemberDashboard('member-1').applications.some(x=>x.id===a.id));assert.throws(()=>r.submitApplication({kind:'event',targetId:'event-1'}),/이미/);r.cancelApplication(a.id);assert.doesNotThrow(()=>r.submitApplication({kind:'event',targetId:'event-1'}));});
test('full and closed events reject submissions',()=>{r.resetDemo();r.setRole('member');assert.throws(()=>r.submitApplication({kind:'event',targetId:'event-10'}),/접수할 수/);assert.throws(()=>r.submitApplication({kind:'event',targetId:'event-6'}),/접수할 수/);assert.throws(()=>r.submitApplication({kind:'event',targetId:'event-1',applicationType:'team',teamSize:0}),/인원/);});
test('admin approval and required rejection reason',()=>{r.resetDemo();r.setRole('member');const a=r.submitApplication({kind:'club',targetId:'club-1'});assert.throws(()=>r.adminStatus(a.id,'승인'),/관리자/);r.setRole('admin');assert.throws(()=>r.adminStatus(a.id,'반려'),/사유/);r.adminStatus(a.id,'반려','확인 필요');assert.equal(r.getMemberDashboard('member-1').applications[0].reason,'확인 필요');});
test('learning requires enrollment, 3 steps, reading and correct answer',()=>{r.resetDemo();r.setRole('member');assert.throws(()=>r.progressStep('course-1',0),/신청 후/);r.submitApplication({kind:'course',targetId:'course-1'});assert.throws(()=>r.completeCourse('course-1',{read:true,answer:'stop'}));[0,1,2].forEach(i=>r.progressStep('course-1',i));assert.throws(()=>r.completeCourse('course-1',{read:false,answer:'stop'}));assert.throws(()=>r.completeCourse('course-1',{read:true,answer:'continue'}));assert.throws(()=>r.completeCourse('course-1',{read:true,answer:'stop'}),/영상/);r.markVideoComplete('course-1');r.completeCourse('course-1',{read:true,answer:'stop'});assert.equal(r.getMemberDashboard('member-1').progress[0].status,'완료');});
test('approved qualification produces certificate and permits issue/reissue',()=>{r.resetDemo();r.setRole('member');const a=r.submitApplication({kind:'qualification',targetId:'qual-2'});r.setRole('admin');r.adminStatus(a.id,'합격');r.setRole('member');const c=r.getMemberDashboard('member-1').certificates.find(c=>c.programId==='qual-2');assert.throws(()=>r.issueCertificate(c.id,true),/최초/);assert.ok(r.issueCertificate(c.id).issuedAt);assert.equal(r.issueCertificate(c.id,true).status,'재발급 완료');});
test('notifications preview validates recipients and queues without claiming delivery',()=>{r.resetDemo();r.setRole('admin');assert.ok(previewMessage('selected',{event:'컵',venue:'부스',time:'8시',items:'물'}).includes('부스'));assert.throws(()=>simulateSend('selected',[],{}),/대상/);simulateSend('selected',['vol-app-1'],{event:'컵',venue:'부스',time:'8시',items:'물'});assert.equal(r.state().notifications[0].status,'발송 대기');});
test('HTML escaping and reset clear demo mutations',()=>{assert.equal(esc('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;');r.resetDemo();r.setRole('admin');r.saveRecord('events','event-1',{title:'수정 대회'});assert.equal(r.getEvent('event-1').title,'수정 대회');r.resetDemo();assert.notEqual(r.getEvent('event-1').title,'수정 대회');assert.equal(r.getRole(),'guest');});

test('inquiry retains the submitted title, body and category',()=>{r.resetDemo();r.saveInquiry('안전 제안',{title:'현장 안내 개선',body:'안내 표지 위치를 개선해주세요.\n입구에서 확인하기 어렵습니다.'});const inquiry=r.state().inquiries.at(-1);assert.equal(inquiry.title,'현장 안내 개선');assert.equal(inquiry.body,'안내 표지 위치를 개선해주세요.\n입구에서 확인하기 어렵습니다.');assert.equal(inquiry.category,'안전 제안');assert.equal(inquiry.status,'접수');r.resetDemo();});
