"""Build CSS and documentation metadata from the canonical JSON token file."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
source = json.loads((root / 'assets/design-system/tokens.json').read_text(encoding='utf-8'))
tokens = [t for group in source['groups'] for t in group['tokens']]
names = [t['name'] for t in tokens]
if len(names) != len(set(names)):
    raise ValueError('Duplicate token name')
css = ['/* Generated by scripts/build-design-tokens.py. Edit tokens.json. */', ':root, [data-ds-theme="light"] {']
for group in source['groups']:
    css.append(f"  /* {group['title']} */")
    css.extend(f"  {t['name']}: {t['value']};" for t in group['tokens'])
css.append('}')
css.append('[data-ds-theme="dark"] {')
css.extend(f"  {t['name']}: {t.get('dark', t['value'])};" for t in tokens if 'dark' in t or 'var(' in t['value'])
css.append('}')
for t in tokens:
    if t['name'].startswith('--type-') and t['name'].endswith('-size'):
        name=t['name'][7:-5]
        css.append(f'.type-{name} {{ font-size:var(--type-{name}-size); line-height:var(--type-{name}-line); letter-spacing:var(--type-{name}-tracking); }}')
(root / 'assets/css/tokens.css').write_text('\n'.join(css)+'\n',encoding='utf-8')
(root / 'assets/js/design-system/tokens.js').write_text('/* Generated. */\nexport const tokenGroups = '+json.dumps(source['groups'],ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
print(f'Built {len(tokens)} tokens in {len(source["groups"])} groups.')
